defaults: &defaults
  :log_level: warn
  :mongo:
    :host: localhost
    :database:
    :port: 27017
    
:development:
  <<: *defaults
  :log_level: debug
  :mongo:
    :host: localhost
    :database:
    :port: 27017

:test:
  <<: *defaults
  :mongo:
    :host:
    :database:
    :port:
    :username:
    :password:

:production:
  <<: *defaults
  :mongo:
    :host:
    :database:
    :port:
    :username:
    :password:
